### ISSUE TITLE
Email sign up set to localhost instead of production domain

### ISSUE THREAD

**Issue by jwu910** [help-is-here/hih#35]
## Description
Unable to confirm user account if not working with a local dev server running

`https://uyaavbhijszzhnnghutr.supabase.co/auth/v1/verify?token=949c46b95159e&type=signup&redirect_to=http://localhost:5173`

We could set a base domain or some similar variable at the environment level that this can populate from, otherwise maybe we default it to w/e production domain we choose?

**Comment by ParisPianist196** [comment]
~~Vite has a base_url env variable we can use.~~

~~This applies to all auth flows and I think we can do the work in one ticket. Updating the description~~

**Comment by ParisPianist196** [comment]
I was wrong. Ignore the things
